ProjetoPedidos/EmissorPedidos/Controllers/EmpresaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EmissorPedidos.Interfaces.Repositories;
using EmissorPedidos.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmissorPedidos.Controllers
{
    public class EmpresaController : Controller
    {
        private readonly IEstadoRepository _estadoRepository;
        private readonly IPaisRepository _paisRepository;
        private readonly IEmpresaRepository _empresaRepository;

        
        public EmpresaController(IEstadoRepository estadoRepository, IPaisRepository paisRepository,
            IEmpresaRepository empresaRepository)
        {
            _estadoRepository = estadoRepository;
            _paisRepository = paisRepository;
            _empresaRepository = empresaRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Cadastro()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult SalvarEmpresa(Empresa empresa)
        {
            var idEmpresa = _empresaRepository.SalvarCadastroEmpresa(empresa);

            return Json(new { });
        }

        //[HttpPost]
        //public IActionResult SalvarEnderecoEmpresa(Enderecos endereco)
        //{

        //}
    }
}

ProjetoPedidos/EmissorPedidos/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EmissorPedidos.Models;
using Microsoft.AspNetCore.Authorization;

namespace EmissorPedidos.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjetoPedidos/EmissorPedidos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="ui grid">
    <div class="four wide column">
        <div class="ui card">
            <div class="content">
                <div class="header">
                    Cadastros
                </div>
            </div>
            <div class="content">
                <h4 class="ui sub header">
                    Empresas
                </h4>
                <div class="ui small feed">
                    <div class="event">
                        <div class="content">
                            <div class="summary">
                                <a asp-controller="Empresa" asp-action="Cadastro">Cadastre aqui</a> sua empresa
                            </div>
                        </div>
                    </div>
                </div>
            </div>            
        </div>
        </div>
    <div class="four wide column">
        <div class="ui card">
            LALALALA
        </div>
    </div>
    <div class="four wide column">
        <div class="ui card">
            LALALALA
        </div>
    </div>
    <div class="four wide column">
        <div class="ui card">
            LALALALA
        </div>
    </div>
</div>